### ISSUE TITLE
Add tests to each task

### ISSUE THREAD

**Issue by lpaulmp** [stackbuilders/sb-debian-base#100]
There some alternatives in order add tests:
- [Ansible Assertion](http://docs.ansible.com/ansible/latest/assert_module.html)
- [Test Kitchen](https://github.com/neillturner/kitchen-ansible)
- [Testinfra](https://github.com/philpep/testinfra)

**Comment by po5i** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add tests to each task](https://trello.com/c/gCLZvvtt/54-add-tests-to-each-task)

**Comment by po5i** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add tests to each task](https://trello.com/c/gCLZvvtt/54-add-tests-to-each-task)
