### ISSUE TITLE
No package matching on Ubuntu 18.04

### ISSUE THREAD

**Issue by roberto910907** [stackbuilders/sb-debian-base#114]
Hey team, it looks like this role is failing on Ubuntu 18.04 when trying to install emacs24-nox package.

https://github.com/stackbuilders/sb-debian-base/blob/master/defaults/main.yml#L30: 

`failed: [production01] (item=[u'atop', u'bash-completion', u'curl', u'emacs24-nox', u'git', u'htop', u'libgmp-dev', u'tmux', u'tree', u'vim', u'postgresql-client-common', u'postgresql-client-9.6', u'libpng-dev', u'python-pip']) => {"changed": false, "item": ["atop", "bash-completion", "curl", "emacs24-nox", "git", "htop", "libgmp-dev", "tmux", "tree", "vim", "postgresql-client-common", "postgresql-client-9.6", "libpng-dev", "python-pip"], "msg": "No package matching 'emacs24-nox' is available"}`

This is because they've moved from emacs24 to emacs25. [emacs-nox doc](https://ubuntu.pkgs.org/18.04/ubuntu-universe-amd64/emacs-nox_47.0_all.deb.html).

> Changelog
2016-12-28 - Rob Browning <rlb@defaultvalue.org>
emacs-defaults (47.0~exp1) experimental; urgency=medium
> * Switch from emacs24 to emacs25.

**Comment by pibism** [comment]
@roberto910907

**Comment by pibism** [comment]
@roberto910907, thank you for your report, the issue has been resolved on the commit #123.
