### ISSUE TITLE
Update location of Stack's Debian package repository

### ISSUE THREAD

**Issue by jpvillaisaza** [stackbuilders/sb-debian-base#17]
As of [Stack 0.1.10.0](https://github.com/commercialhaskell/stack/releases/tag/v0.1.10.0), the locations of Stack's [Ubuntu](http://docs.haskellstack.org/en/stable/install_and_upgrade.html#ubuntu) and [Debian](http://docs.haskellstack.org/en/stable/install_and_upgrade.html#debian) package repositories changed to have correct URL semantics (see commercialhaskell/stack#1378). Even though the old locations will work for some months, they suggest adjusting to the new ones. Thus, the "Add FPCO Deb repository" task here should be updated.

**Comment by sestrella** [comment]
@jpvillaisaza, @lpaulmp, @jsl, @goetzc maybe is worth it to extract all Haskell tasks to a separate Galaxy itself. That way we could support more distributions and make Haskell Stack installation more configurable.

**Comment by sestrella** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [sb-debian-base - Update location of Stack's Debian package repository](https://trello.com/c/Z2zDLwc9/4-sb-debian-base-update-location-of-stack-s-debian-package-repository)

**Comment by goetzc** [comment]
It seems that the YUM and APT repositories [where removed](https://github.com/commercialhaskell/stack/commit/4a69b616c67e29a4c7de9f4d75528317fa1cc761#diff-0e106df41e1dcadc38b068b7116d301fL113) last December from the docs, although they are still available for the time being.

**Comment by jpvillaisaza** [comment]
@goetzc I don't remember how this is configured to install Stack, but the issue is probably not relevant anymore. The recommended way to install Stack now is to use the [generic Linux option](https://docs.haskellstack.org/en/stable/install_and_upgrade/#linux), which uses [a script](https://get.haskellstack.org/). Taking a look at that and updating accordingly is probably a better option here.

**Comment by lpaulmp** [comment]
I'm working in this PR to close this issue https://github.com/stackbuilders/haskell-stack/pull/1

**Comment by po5i** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update location of Stack's Debian package repository](https://trello.com/c/mZ5zEThu/56-update-location-of-stacks-debian-package-repository)

**Comment by lpaulmp** [comment]
@goetzc this repo https://github.com/stackbuilders/haskell-stack would help to remove Stack from  sb-debian-base

**Comment by speedlight** [comment]
We are closing this issue in favor of #135 implementation
