### ISSUE TITLE
Setup continuous integration

### ISSUE THREAD

**Issue by sestrella** [stackbuilders/sb-debian-base#47]
In order to ensure all role tasks run properly on the listed supported versions of Debian and Ubuntu. We need to setup a continuous integration service and run the Ansible role against different Debian containers.

## First Approach (just checking the role runs properly)

- Configure the repo to run on Travis.
- Enable [docker](https://docs.travis-ci.com/user/docker) support.
- Run the role on different docker Debian [containers](http://blog.oddbit.com/2015/10/13/ansible-20-the-docker-connection-driver).

## Second Approach (testing a little bit more deeply)

- Setup [test-kitchen](https://github.com/test-kitchen/test-kitchen) with docker driver.
- Write some [unit tests](http://es.slideshare.net/MartinEtmajer/testing-ansible-roles-with-test-kitchen-serverspec-and-rspec-48185017).
- Configure the build on Travis.

**Comment by sestrella** [comment]
@jsl, @00dav00, @00dav00 any comments?

**Comment by 00dav00** [comment]
I think that we may use the approaches above as phases.
* 1st phase: Get the docker containers properly configured on Travis and verify correct execution of the playbooks, meaning only no exceptions was raised.
*2nd phase: With the containers in place we can start the configuration of `test-kitchen` and start making assertions about the expected outcome of the provision.

I think it would also be handy to have a prioritized list of OS versions to work on.

WDYT?

**Comment by sestrella** [comment]
@00dav00 sounds reasonable we could use the first approach as a base-line for the second one.

**Comment by sestrella** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [hapistrano - Setup continuous integration](https://trello.com/c/fbalRogr/1-hapistrano-setup-continuous-integration)

**Comment by CristhianMotoche** [comment]
Hey guys, if you don't mind I'd like to solve this issue. I'll be asking you for help. Do you agree? @00dav00 @goetzc @lpaulmp
