### ISSUE TITLE
Standarize variables names

### ISSUE THREAD

**Issue by sestrella** [stackbuilders/sb-debian-base#48]
There is some inconsistency across variables name. For instance, the variable name for admin user is called `admin_user`  while the deploy user variable name is `deploy_username`. Also looks like most Ansible Galaxies prefix the Galaxy name to the variable names. Maybe we could name variables like:

```
admin_user => sb_debian_base_admin_user
deploy_username => sb_debian_base_deploy_user
...
```

### References
- https://github.com/ANXS/postgresql#variables
- https://github.com/geerlingguy/ansible-role-nginx#role-variables

**Comment by sestrella** [comment]
@jsl, @00dav00, @goetzc, @lpaulmp could you guys take a look please.

**Comment by goetzc** [comment]
This seems to be a sensible idea, to avoid ending up mixing variables names.

**Comment by lpaulmp** [comment]
:+1:  to standardize variables names.

**Comment by sestrella** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [sb-debian-base - Standarize variables names](https://trello.com/c/T47ul1EH/2-sb-debian-base-standarize-variables-names)
