### ISSUE TITLE
Add tag to update SSH keys only

### ISSUE THREAD

**Issue by CristhianMotoche** [stackbuilders/sb-debian-base#51]
Issue created from trello card: https://trello.com/c/qBzyYbIq/9-sb-debian-base-add-tag-to-update-ssh-keys-only

**Comment by CristhianMotoche** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [sb-debian-base - Add tag to update SSH keys only](https://trello.com/c/qBzyYbIq/9-sb-debian-base-add-tag-to-update-ssh-keys-only)

**Comment by goetzc** [comment]
For future reference, there is already the `add-remove-keys` tag.

**Comment by CristhianMotoche** [comment]
Yeah. I left that comment in the Trello card. Thanks @goetzc
