### ISSUE TITLE
Add GitHub topics

### ISSUE THREAD

**Issue by goetzc** [stackbuilders/sb-debian-base#52]
For ease of search:  
https://github.com/blog/2309-introducing-topics

And also improve description.

**Comment by sestrella** [comment]
@goetzc I added `ansible`, `debian` and `ubuntu` looks good to you?

**Comment by goetzc** [comment]
Looks good, thanks @sestrella!

**Comment by goetzc** [comment]
@sestrella can you also add `ansible-role`? Which is used by other roles too, like [ANXS](https://github.com/ANXS/).

**Comment by sestrella** [comment]
@goetzc sure thing
