### ISSUE TITLE
Create a change log for the project

### ISSUE THREAD

**Issue by 00dav00** [stackbuilders/sb-debian-base#60]
In order to keep track of the project changes in a more transparent way, I think it would be a good idea to create a change log that reflects what is added or removed.

WDYT @lpaulmp @jsl @sestrella @goetzc ?

**Comment by goetzc** [comment]
Yes, sure. We have the one from [releases](https://github.com/stackbuilders/sb-debian-base/releases), we can copy it into a  `CHANGELOG.md` file.

**Comment by lpaulmp** [comment]
@00dav00 Sounds good idea
