### ISSUE TITLE
Rbenv?

### ISSUE THREAD

**Issue by IlkhamGaysin** [stackbuilders/sb-debian-base#88]
Rbenv is lightweight  tool for the managing ruby versions, we don't need to manage gems via rvm because bundler is intended for that.
https://github.com/stackbuilders/sb-debian-base#ruby-dependencies-ruby-dependencies

https://github.com/rbenv/rbenv/wiki/Why-rbenv%3F

Deployment with rbenv:
https://github.com/rbenv/rbenv/wiki/Deploying-with-rbenv

**Comment by goetzc** [comment]
I think we should just remove that [task](https://github.com/stackbuilders/sb-debian-base/blob/master/tasks/ruby-dependencies.yml) from this role, as it only installs a list of deb packages from the repo, not very useful and considering that a role for rvm or rbenv is still required.

**Comment by lpaulmp** [comment]
@IlkhamGaysin  @goetzc we can overwrite the list of dependencies, right?

**Comment by goetzc** [comment]
As the task has been removed (#90) in favor of using a proper role like [zzet/ansible-rbenv-role](https://github.com/zzet/ansible-rbenv-role), I'm closing this one. Thanks for bringing this up @IlkhamGaysin!
