### ISSUE TITLE
Allow a list of development platforms to be added as known hosts

### ISSUE THREAD

**Issue by 00dav00** [stackbuilders/sb-debian-base#91]
Github is the most popular development platform (the industry default to host code) but not  the only one. 

Currently `sb-debian-base` only [adds Github as a known host](https://github.com/stackbuilders/sb-debian-base/blob/master/tasks/bootstrap-deploy-user.yml#L34-L42), it would be great if the known hosts could come from a list which default value is ` - github.com `.

**Comment by lpaulmp** [comment]
@00dav0 Sounds good thanks for opening this issue, then I'll move this as defaults variables so you can overwrite when this is needed.

**Comment by lpaulmp** [comment]
@00dav00 Closing this issue.
