### ISSUE TITLE
Add additional apt repositories along with keys

### ISSUE THREAD

**Issue by 00dav00** [stackbuilders/sb-debian-base#97]
Often while bootstraping a server, some packages will be required to be present. At the moment this is handled by adding items to `sb_debian_base_extra_packages` variable, but not all packages are avaiable in default repositories.

As a `sb-debian-base` user I would like the role to allow me to add new repos (with their corresponding keys), so that I can install packages not present in default apt repositories.

**Comment by 00dav00** [comment]
@goetzc @lpaulmp I can create a PR for this. @goetzc mentioned that something similar was implemented in another project so I can used that as a base. WDYT?

**Comment by lpaulmp** [comment]
@00dav00 Sounds good, please go ahead open a PR.

**Comment by po5i** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add additional apt repositories along with keys](https://trello.com/c/EPjPo5Qy/55-add-additional-apt-repositories-along-with-keys)

**Comment by speedlight** [comment]
Discussed with @nickovivar and @juanpaucar: Installing packages which aren't in main repo branch like stable in Debian we think is better to have explicit tasks for this packages that need installation from other sources.
